INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('Manufacturer_Name','Manufacturer','*'),
	 ('Manufacturer_PN','PartNumber','*'),
	 ('Part_Type','PartType','*'),
	 ('Error_code','ErrorCode',NULL),
	 ('SE_MFR','SE_MFR',NULL),
	 ('SE_MPN','SE_MPN',NULL),
	 ('SE_Lifecycle','SE_Lifecycle',NULL),
	 ('BU','BU','*'),
	 ('Applicant','Applicant','*'),
	 ('Tracking_Number','Tracking_Number','*');
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('Silicon_Expert_Path_1st','TaxonomyPath',NULL),
	 ('Silicon_Expert_Path_2nd','TaxonomyPath',NULL),
	 ('Silicon_Expert_Path_3rd','TaxonomyPath',NULL),
	 ('Silicon_Expert_Description','PartDescription',NULL),
	 ('Operating_Temperature_Min_(C)','Minimum Operating Temperature','*'),
	 ('Operating_Temperature_Max_(C)','Maximum Operating Temperature','*'),
	 ('Mount_Type','Mounting','*'),
	 ('Package_Type','Package/Case;Supplier Package;Package Family Name;Basic Package Type','*'),
	 ('Product_Length','Package Overall Length;Product Length','*'),
	 ('Length_Tol','Length Tolerance','*');
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('Length_Max','Maximum Product Length',NULL),
	 ('Product_Width','Package Overall Width;Product Depth;Product Width','*'),
	 ('Width_Tol','Depth Tolerance;Width Tolerance','*'),
	 ('Width_Max','Maximum Product Depth;Maximum Product Width',NULL),
	 ('Product_Height','Seated Plane Height;Package Overall Height;Product Height','*'),
	 ('Height_Tol','Height Tolerance','*'),
	 ('Height_Max','Maximum Product Height',NULL),
	 ('Package_Length','Package Length',NULL),
	 ('Package_Width','Package Width',NULL),
	 ('Package_Height','Package Height',NULL);
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('PDF_File','PDF_file',NULL),
	 ('DATA_SHEET','Datasheet',NULL),
	 ('SE_JSON','SE_JSON',NULL),
	 ('Automotive','Automotive',NULL),
	 ('AEC_Qualified','AEC Qualified',NULL),
	 ('PDM_CATEGORY','ITPDM_CATEGORY',NULL),
	 ('PDM_Create_Date','ITPDM_Create_Date',NULL),
	 ('PDM_ENPD_insert_stamp','ITPDM_ENPD_insert_stamp',NULL),
	 ('PDM_GREEN_DESCRIPTION','ITPDM_Green_Description',NULL),
	 ('PDM_GREEN_STATUS','ITPDM_GREEN_STATUS',NULL);
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('PDM_LIFE_TIME','ITPDM_LIFE_TIME',NULL),
	 ('PDM_Mfr_Lifecycle_Phase','ITPDM_Mfr_Lifecycle_Phase',NULL),
	 ('PDM_Mfr_Part_Lifecycle_Phase','ITPDM_Mfr_Part_Lifecycle_Phase',NULL),
	 ('PDM_Modify_date','ITPDM_Modify_date',NULL),
	 ('PDM_MPN_DESCRIPTION','ITPDM_MPN_DESCRIPTION',NULL),
	 ('PDM_MPN_DESCRIPTION_2','ITPDM_MPN_DESCRIPTION_2',NULL),
	 ('PDM_PART_NUMBER','ITPDM_PART_NUMBER',NULL),
	 ('PDM_PDM_DATA_SHEET','ITPDM_PDM_DATA_SHEET',NULL),
	 ('PDM_PRICE','ITPDM_PRICE',NULL),
	 ('PDM_PRICE_TYPE','ITPDM_PRICE_TYPE',NULL);
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('PDM_ROHS_2_0','ITPDM_ROHS_2_0',NULL),
	 ('PDM_ROHS_EXEMPTION','ITPDM_RoHS_Exemption',NULL),
	 ('PDM_USI_PN_DESCRIPTION','ITPDM_USI_PN_DESCRIPTION',NULL),
	 ('PRIORITY',NULL,NULL),
	 ('MLCC---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('MLCC---Capacitance','Capacitance;Capacitance Value','*'),
	 ('MLCC---Capacitance_Value','Capacitance Value UnitedValue','*'),
	 ('MLCC---Capacitance_Unit','Capacitance Value UnitedUnit','*'),
	 ('MLCC---Tolerance','Tolerance','*'),
	 ('MLCC---DC_Rated_Voltage_(VDC)','DC Rated Voltage','*');
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('MLCC---Voltage','Voltage','*'),
	 ('MLCC---Temperature_Coefficient','Dielectric','*'),
	 ('MLCC_Networks_and_Array---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('MLCC_Networks_and_Array---Capacitance','Capacitance;Capacitance Value','*'),
	 ('MLCC_Networks_and_Array---Capacitance_Value','Capacitance Value UnitedValue','*'),
	 ('MLCC_Networks_and_Array---Capacitance_Unit','Capacitance Value UnitedUnit','*'),
	 ('MLCC_Networks_and_Array---Tolerance','Tolerance','*'),
	 ('MLCC_Networks_and_Array---DC_Rated_Voltage_(VDC)','DC Rated Voltage','*'),
	 ('MLCC_Networks_and_Array---Voltage','Voltage','*'),
	 ('MLCC_Networks_and_Array---Temperature_Coefficient','Dielectric','*');
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('Battery---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts',NULL),
	 ('Battery---Rechargeable','Non-Rechargeable/Rechargeable',NULL),
	 ('Battery---Shape','Shape',NULL),
	 ('Battery---Voltage_(V)','Voltage','*'),
	 ('Battery---Capacity_(Ah)','Capacity','*'),
	 ('Battery---Battery_Chemistry','Battery Chemistry;Chemistry',NULL),
	 ('Battery---Diameter','Product Diameter;Package Diameter','*'),
	 ('Buzzer---Resonant_Frequency_Max_(Hz)','Maximum Resonant Frequency (Hz)',NULL),
	 ('Buzzer---Operating_Supply_Voltage_Max','Maximum Operating Supply Voltage','*'),
	 ('Buzzer---Supply_Current_Max_(mA)','Maximum Supply Current (mA)','*');
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('Buzzer---Sound_Pressure_Min_(dBA)','Minimum Sound Pressure (dBA)','*'),
	 ('Buzzer---Type','Type',NULL),
	 ('Buzzer---Technology','Technology',NULL),
	 ('Capacitor_Aluminum_Electrolytic---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('Capacitor_Aluminum_Electrolytic---Device_Type','Type;Device Type;Construction;Case Style;Technology',NULL),
	 ('Capacitor_Aluminum_Electrolytic---Capacitance','Capacitance;Capacitance Value','*'),
	 ('Manufacturer_Name','Manufacturer','*'),
	 ('Manufacturer_PN','PartNumber','*'),
	 ('Part_Type','PartType','*'),
	 ('Error_code','ErrorCode',NULL);
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('SE_MFR','SE_MFR',NULL),
	 ('SE_MPN','SE_MPN',NULL),
	 ('SE_Lifecycle','SE_Lifecycle',NULL),
	 ('BU','BU','*'),
	 ('Applicant','Applicant','*'),
	 ('Tracking_Number','Tracking_Number','*'),
	 ('Silicon_Expert_Path_1st','TaxonomyPath',NULL),
	 ('Silicon_Expert_Path_2nd','TaxonomyPath',NULL),
	 ('Silicon_Expert_Path_3rd','TaxonomyPath',NULL),
	 ('Silicon_Expert_Description','PartDescription',NULL);
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('Operating_Temperature_Min_(C)','Minimum Operating Temperature','*'),
	 ('Operating_Temperature_Max_(C)','Maximum Operating Temperature','*'),
	 ('Mount_Type','Mounting','*'),
	 ('Package_Type','Package/Case;Supplier Package;Package Family Name;Basic Package Type','*'),
	 ('Product_Length','Package Overall Length;Product Length','*'),
	 ('Length_Tol','Length Tolerance','*'),
	 ('Length_Max','Maximum Product Length',NULL),
	 ('Product_Width','Package Overall Width;Product Depth;Product Width','*'),
	 ('Width_Tol','Depth Tolerance;Width Tolerance','*'),
	 ('Width_Max','Maximum Product Depth;Maximum Product Width',NULL);
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('Product_Height','Seated Plane Height;Package Overall Height;Product Height','*'),
	 ('Height_Tol','Height Tolerance','*'),
	 ('Height_Max','Maximum Product Height',NULL),
	 ('Package_Length','Package Length',NULL),
	 ('Package_Width','Package Width',NULL),
	 ('Package_Height','Package Height',NULL),
	 ('PDF_File','PDF_file',NULL),
	 ('DATA_SHEET','Datasheet',NULL),
	 ('SE_JSON','SE_JSON',NULL),
	 ('Automotive','Automotive',NULL);
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('AEC_Qualified','AEC Qualified',NULL),
	 ('PDM_CATEGORY','ITPDM_CATEGORY',NULL),
	 ('PDM_Create_Date','ITPDM_Create_Date',NULL),
	 ('PDM_ENPD_insert_stamp','ITPDM_ENPD_insert_stamp',NULL),
	 ('PDM_GREEN_DESCRIPTION','ITPDM_Green_Description',NULL),
	 ('PDM_GREEN_STATUS','ITPDM_GREEN_STATUS',NULL),
	 ('PDM_LIFE_TIME','ITPDM_LIFE_TIME',NULL),
	 ('PDM_Mfr_Lifecycle_Phase','ITPDM_Mfr_Lifecycle_Phase',NULL),
	 ('PDM_Mfr_Part_Lifecycle_Phase','ITPDM_Mfr_Part_Lifecycle_Phase',NULL),
	 ('PDM_Modify_date','ITPDM_Modify_date',NULL);
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('PDM_MPN_DESCRIPTION','ITPDM_MPN_DESCRIPTION',NULL),
	 ('PDM_MPN_DESCRIPTION_2','ITPDM_MPN_DESCRIPTION_2',NULL),
	 ('PDM_PART_NUMBER','ITPDM_PART_NUMBER',NULL),
	 ('PDM_PDM_DATA_SHEET','ITPDM_PDM_DATA_SHEET',NULL),
	 ('PDM_PRICE','ITPDM_PRICE',NULL),
	 ('PDM_PRICE_TYPE','ITPDM_PRICE_TYPE',NULL),
	 ('PDM_ROHS_2_0','ITPDM_ROHS_2_0',NULL),
	 ('PDM_ROHS_EXEMPTION','ITPDM_RoHS_Exemption',NULL),
	 ('PDM_USI_PN_DESCRIPTION','ITPDM_USI_PN_DESCRIPTION',NULL),
	 ('PRIORITY',NULL,NULL);
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('MLCC---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('MLCC---Capacitance','Capacitance;Capacitance Value','*'),
	 ('MLCC---Capacitance_Value','Capacitance Value UnitedValue','*'),
	 ('MLCC---Capacitance_Unit','Capacitance Value UnitedUnit','*'),
	 ('MLCC---Tolerance','Tolerance','*'),
	 ('MLCC---DC_Rated_Voltage_(VDC)','DC Rated Voltage','*'),
	 ('MLCC---Voltage','Voltage','*'),
	 ('MLCC---Temperature_Coefficient','Dielectric','*'),
	 ('MLCC_Networks_and_Array---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('MLCC_Networks_and_Array---Capacitance','Capacitance;Capacitance Value','*');
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('MLCC_Networks_and_Array---Capacitance_Value','Capacitance Value UnitedValue','*'),
	 ('MLCC_Networks_and_Array---Capacitance_Unit','Capacitance Value UnitedUnit','*'),
	 ('MLCC_Networks_and_Array---Tolerance','Tolerance','*'),
	 ('MLCC_Networks_and_Array---DC_Rated_Voltage_(VDC)','DC Rated Voltage','*'),
	 ('MLCC_Networks_and_Array---Voltage','Voltage','*'),
	 ('MLCC_Networks_and_Array---Temperature_Coefficient','Dielectric','*'),
	 ('Battery---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts',NULL),
	 ('Battery---Rechargeable','Non-Rechargeable/Rechargeable',NULL),
	 ('Battery---Shape','Shape',NULL),
	 ('Battery---Voltage_(V)','Voltage','*');
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('Battery---Capacity_(Ah)','Capacity','*'),
	 ('Battery---Battery_Chemistry','Battery Chemistry;Chemistry',NULL),
	 ('Battery---Diameter','Product Diameter;Package Diameter','*'),
	 ('Buzzer---Resonant_Frequency_Max_(Hz)','Maximum Resonant Frequency (Hz)',NULL),
	 ('Buzzer---Operating_Supply_Voltage_Max','Maximum Operating Supply Voltage','*'),
	 ('Buzzer---Supply_Current_Max_(mA)','Maximum Supply Current (mA)','*'),
	 ('Buzzer---Sound_Pressure_Min_(dBA)','Minimum Sound Pressure (dBA)','*'),
	 ('Buzzer---Type','Type',NULL),
	 ('Buzzer---Technology','Technology',NULL),
	 ('Capacitor_Aluminum_Electrolytic---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*');
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('Capacitor_Aluminum_Electrolytic---Device_Type','Type;Device Type;Construction;Case Style;Technology',NULL),
	 ('Capacitor_Aluminum_Electrolytic---Capacitance','Capacitance;Capacitance Value','*'),
	 ('Capacitor_Aluminum_Electrolytic---DC_Rated_Voltage_(VDC)','DC Rated Voltage','*'),
	 ('Capacitor_Aluminum_Electrolytic---Voltage','Voltage','*'),
	 ('Capacitor_Aluminum_Electrolytic---Equivalent_Series_Resistance','Equivalent Series Resistance',NULL),
	 ('Capacitor_Aluminum_Electrolytic---Leakage_Current_(uA)','Leakage Current',NULL),
	 ('Capacitor_Aluminum_Electrolytic---Lifetime_(h)','Lifetime','*'),
	 ('Capacitor_Aluminum_Electrolytic---Dissipation_Factor_Max','Maximum Dissipation Factor',NULL),
	 ('Capacitor_Aluminum_Electrolytic---Ripple_Current_(mA)','Ripple Current',NULL),
	 ('Capacitor_Aluminum_Electrolytic---Tolerance','Tolerance','*');
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('Capacitor_Aluminum_Electrolytic---Product_Diameter_(mm)','Product Diameter;Package Diameter','*'),
	 ('Capacitor_Aluminum_Polymer---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('Capacitor_Aluminum_Polymer---Capacitance','Capacitance;Capacitance Value','*'),
	 ('Capacitor_Aluminum_Polymer---Tolerance','Tolerance','*'),
	 ('Capacitor_Aluminum_Polymer---Equivalent_Series_Resistance_(R)','Equivalent Series Resistance',NULL),
	 ('Capacitor_Aluminum_Polymer---DC_Rated_Voltage_(VDC)','DC Rated Voltage','*'),
	 ('Capacitor_Aluminum_Polymer---Voltage','Voltage','*'),
	 ('Capacitor_Aluminum_Polymer---Lifetime_(h)','Lifetime','*'),
	 ('Capacitor_Aluminum_Polymer---Dissipation_Factor_Max','Maximum Dissipation Factor',NULL),
	 ('Capacitor_Aluminum_Polymer---Ripple_Current_(mA)','Ripple Current','*');
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('Capacitor_Aluminum_Polymer---Leakage_Current_(uA)','Leakage Current',NULL),
	 ('Capacitor_Aluminum_Polymer---Product_Diameter_(mm)','Product Diameter','*'),
	 ('Capacitor_Aluminum_Polymer---Type','Type',NULL),
	 ('Capacitor_Tantalum_Polymer---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('Capacitor_Tantalum_Polymer---Capacitance','Capacitance;Capacitance Value','*'),
	 ('Capacitor_Tantalum_Polymer---Tolerance','Tolerance','*'),
	 ('Capacitor_Tantalum_Polymer---DC_Rated_Voltage_(VDC)','DC Rated Voltage','*'),
	 ('Capacitor_Tantalum_Polymer---Voltage','Voltage','*'),
	 ('Capacitor_Tantalum_Polymer---Equivalent_Series_Resistance_(R)','Equivalent Series Resistance',NULL),
	 ('Capacitor_Tantalum_Polymer---Dissipation_Factor_Max','Maximum Dissipation Factor',NULL);
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('Capacitor_Tantalum_Polymer---Ripple_Current_(mA)','Ripple Current',NULL),
	 ('Capacitor_Tantalum_Polymer---Leakage_Current_(uA)','Leakage Current',NULL),
	 ('Capacitor_Tantalum_Polymer---Product_Diameter_(mm)','Product Diameter',NULL),
	 ('Capacitor_Tantalum_Polymer---Type','Type',NULL),
	 ('Capacitor_Feed_Through---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts',NULL),
	 ('Capacitor_Feed_Through---Device_Type','Device Type;Construction;Case Style;Technology',NULL),
	 ('Capacitor_Feed_Through---Capacitance','Capacitance;Capacitance Value','*'),
	 ('Capacitor_Feed_Through---Capacitance_Value','Capacitance Value UnitedValue','*'),
	 ('Capacitor_Feed_Through---Capacitance_Unit','Capacitance Value UnitedUnit','*'),
	 ('Capacitor_Feed_Through---Tolerance','Tolerance','*');
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('Capacitor_Feed_Through---Temperature_Coefficient','Dielectric',NULL),
	 ('Capacitor_Feed_Through---DC_Rated_Voltage_(VDC)','DC Rated Voltage','*'),
	 ('Capacitor_Feed_Through---Voltage','Voltage','*'),
	 ('Common_Mode_Choke---Type','Type',NULL),
	 ('Common_Mode_Choke---Number_of_Lines','Number of Lines',NULL),
	 ('Common_Mode_Choke---Inductance_(H)','Inductance','*'),
	 ('Common_Mode_Choke---Leakage_Inductance_(H)','Leakage Inductance',NULL),
	 ('Common_Mode_Choke---Test_Frequency_(Hz)','Inductance Test Frequency',NULL),
	 ('Common_Mode_Choke---Impedance_(R)','Impedance','*'),
	 ('Common_Mode_Choke---DC_Resistance_Max_(R)','Maximum DC Resistance','*');
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('Common_Mode_Choke---DC_Current_Max_(A)','Maximum DC Current','*'),
	 ('Common_Mode_Choke---Withstand_Voltage','Withstand Voltage',NULL),
	 ('Common_Mode_Choke---Voltage_Rating','Voltage Rating','*'),
	 ('Connector_Other---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('Connector_Other---Terminal_Pitch_(mm)','Terminal Pitch',NULL),
	 ('Connector_Other---Contact_Area_Plating','Contact Area Plating;Contact Plating','*'),
	 ('Connector_Other---Contact_Plating_Thickness','Contact Plating Thickness',NULL),
	 ('Connector_Other---Mating_Cycle','Mating Cycle',NULL),
	 ('Connector_Other---Speed_Rating_(Gbps)','Speed Rating',NULL),
	 ('Connector_Other---Contact_Resistance_Max_(mR)','Maximum Contact Resistance',NULL);
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('Connector_Other---Insulation_Material','Insulation Material',NULL),
	 ('Connector_Other---Insulation_Resistance_(MR)','Insulation Resistance',NULL),
	 ('Connector_Other---Current_Rating_Max_(A)','Maximum Current Rating','*'),
	 ('Connector_Other---Voltage_Rating_Max','Maximum Voltage Rating','*'),
	 ('Connector_Other---Housing_Material','Housing Material','*'),
	 ('Connector_Other---Shell_Material','Shell Material',NULL),
	 ('Connector_Other---Housing_Color','Housing Color',NULL),
	 ('Connector_Other---Contact_Material','Contact Material',NULL),
	 ('Connector_Other---Type','Type','*'),
	 ('Connector_Other---Connector_Type','Connector Type',NULL);
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('Conn_Wire_and_PCB---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('Conn_Wire_and_PCB---Terminal_Pitch_(mm)','Terminal Pitch',NULL),
	 ('Conn_Wire_and_PCB---Contact_Area_Plating','Contact Area Plating;Contact Plating','*'),
	 ('Conn_Wire_and_PCB---Contact_Plating_Thickness','Contact Plating Thickness',NULL),
	 ('Conn_Wire_and_PCB---Mating_Cycle','Mating Cycle',NULL),
	 ('Conn_Wire_and_PCB---Speed_Rating_(Gbps)','Speed Rating',NULL),
	 ('Conn_Wire_and_PCB---Contact_Resistance_Max_(mR)','Maximum Contact Resistance',NULL),
	 ('Conn_Wire_and_PCB---Insulation_Material','Insulation Material',NULL),
	 ('Conn_Wire_and_PCB---Insulation_Resistance_(MR)','Insulation Resistance',NULL),
	 ('Conn_Wire_and_PCB---Current_Rating_Max_(A)','Maximum Current Rating','*');
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('Conn_Wire_and_PCB---Voltage_Rating_Max','Maximum Voltage Rating','*'),
	 ('Conn_Wire_and_PCB---Housing_Material','Housing Material','*'),
	 ('Conn_Wire_and_PCB---Shell_Material','Shell Material',NULL),
	 ('Conn_Wire_and_PCB---Housing_Color','Housing Color',NULL),
	 ('Conn_Wire_and_PCB---Contact_Material','Contact Material',NULL),
	 ('Conn_Wire_and_PCB---Type','Type','*'),
	 ('Conn_Wire_and_PCB---Connector_Type','Connector Type',NULL),
	 ('Connector_IO---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('Connector_IO---Terminal_Pitch_(mm)','Terminal Pitch',NULL),
	 ('Connector_IO---Contact_Area_Plating','Contact Area Plating;Contact Plating','*');
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('Connector_IO---Contact_Plating_Thickness','Contact Plating Thickness',NULL),
	 ('Connector_IO---Mating_Cycle','Mating Cycle',NULL),
	 ('Connector_IO---Speed_Rating_(Gbps)','Speed Rating',NULL),
	 ('Connector_IO---Contact_Resistance_Max_(mR)','Maximum Contact Resistance',NULL),
	 ('Connector_IO---Insulation_Material','Insulation Material',NULL),
	 ('Connector_IO---Insulation_Resistance_(MR)','Insulation Resistance',NULL),
	 ('Connector_IO---Current_Rating_Max_(A)','Maximum Current Rating','*'),
	 ('Connector_IO---Voltage_Rating_Max','Maximum Voltage Rating','*'),
	 ('Connector_IO---Housing_Material','Housing Material','*'),
	 ('Connector_IO---Shell_Material','Shell Material',NULL);
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('Connector_IO---Housing_Color','Housing Color',NULL),
	 ('Connector_IO---Contact_Material','Contact Material',NULL),
	 ('Connector_IO---Type','Type','*'),
	 ('Connector_IO---Connector_Type','Connector Type',NULL),
	 ('Connector_Accessorie---Connector_Type','Connector Type',NULL),
	 ('Connector_Accessorie---Type','Type','*'),
	 ('Connector_Accessorie---Plating','Plating',NULL),
	 ('Connector_Accessorie---Material','Material','*'),
	 ('Connector_Accessorie---Body_Plating','Body Plating',NULL),
	 ('Connector_Accessorie---Body_Material','Body Material',NULL);
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('Connector_Battery_Holder---Type','Type',NULL),
	 ('Connector_Battery_Holder---Number_of_Cells','Number of Cells','*'),
	 ('Connector_Battery_Holder---Battery_Series','Battery Series','*'),
	 ('Connector_Battery_Holder---Body_Material','Body Material',NULL),
	 ('Connector_Battery_Holder---Contact_Material','Contact Material',NULL),
	 ('Connector_Battery_Holder---Contact_Plating','Contact Plating',NULL),
	 ('Connector_RF---Type','Type',NULL),
	 ('Connector_RF---Gender','Gender',NULL),
	 ('Connector_RF---Operating_Frequency_(Hz)','Operating Frequency','*'),
	 ('Connector_RF---Impedance_(R)','Impedance','*');
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('Connector_RF---Insulation_Resistance_(MR)','Insulation Resistance','*'),
	 ('Connector_RF---Termination_Method','Termination Method',NULL),
	 ('Connector_RF---Contact_Plating','Contact Plating','*'),
	 ('Connector_RF---Contact_Material','Contact Material',NULL),
	 ('Connector_RF---Body_Plating','Body Plating',NULL),
	 ('Connector_RF---Body_Material','Body Material','*'),
	 ('Connector_RF---Insulator_Material','Insulator Material',NULL),
	 ('Connector_RF---Mating_System','Mating System',NULL),
	 ('Crystal_Oscillator---Type','Type',NULL),
	 ('Crystal_Oscillator---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*');
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('Crystal_Oscillator---Standard_Frequency_(MHz)','Standard Frequency','*'),
	 ('Crystal_Oscillator---Frequency_Stability_(ppm)','Frequency Stability','*'),
	 ('Crystal_Oscillator---Load_Capacitance_(pF)','Load Capacitance','*'),
	 ('Crystal_Oscillator---Symmetry_Max','Maximum Symmetry','*'),
	 ('Crystal_Oscillator---Typical_Operating_Supply_Voltage_(V)','Typical Operating Supply Voltage',NULL),
	 ('Crystal_Oscillator---Operating_Supply_Voltage_Max_(V)','Maximum Operating Supply Voltage (V)','*'),
	 ('Crystal_Oscillator---Operating_Junction_Temperature_(C)','Operating Junction Temperature',NULL),
	 ('Crystal_Oscillator---Junction_Thermal_Resistance_Max','Maximum Junction Ambient Thermal Resistance',NULL),
	 ('Crystals---Type','Type',NULL),
	 ('Crystals---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*');
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('Crystals---Standard_Frequency_(MHz)','Standard Frequency','*'),
	 ('Crystals---Frequency_Tolerance_(ppm)','Frequency Tolerance','*'),
	 ('Crystals---Frequency_Stability_(ppm)','Frequency Stability','*'),
	 ('Crystals---Series_Resistance_(R)','Series Resistance',NULL),
	 ('Crystals---Rated_Current_(A)','Rated Current',NULL),
	 ('Crystals---Power_Dissipation_Max_(mW)','Max Rated Power',NULL),
	 ('Crystals---Load_Capacitance_(pF)','Load Capacitance','*'),
	 ('Diode_ESD_Suppressors---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('Diode_ESD_Suppressors---Type','Type',NULL),
	 ('Diode_ESD_Suppressors---Configuration','Configuration',NULL);
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('Diode_ESD_Suppressors---Working_Voltage_Max_(V)','Maximum Working Voltage','*'),
	 ('Diode_ESD_Suppressors---Breakdown_Voltage_Min_(V)','Minimum Breakdown Voltage',NULL),
	 ('Diode_ESD_Suppressors---Breakdown_Voltage_Max_(V)','Maximum Breakdown Voltage','*'),
	 ('Diode_ESD_Suppressors---Leakage_Current_Max_(uA)','Maximum Leakage Current','*'),
	 ('Diode_ESD_Suppressors---Clamping_Voltage_Max_(V)','Maximum Clamping Voltage','*'),
	 ('Diode_ESD_Suppressors---Power_Dissipation_Max_(mW)','Maximum Power Dissipation','*'),
	 ('Diode_ESD_Suppressors---Operating_Junction_Temperature_(C)','Operating Junction Temperature','*'),
	 ('Diode_ESD_Suppressors---Junction_Thermal_Resistance_Max','Maximum Junction Ambient Thermal Resistance',NULL),
	 ('Diode_ESD_Suppressors---Avalanche_Current_(uA)','Avalanche Current',NULL),
	 ('Diode_ESD_Suppressors---Capacitance_Value','Capacitance Value',NULL);
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('Diode_ESD_Suppressors---Continuous_Forward_Current_Max','Maximum Continuous Forward Current',NULL),
	 ('Diode_Rectifier---DC_Reverse_Voltage_Max_(V)','Maximum DC Reverse Voltage;','*'),
	 ('Diode_Rectifier---Peak_Reverse_Repetitive_Voltage_(V)','Peak Reverse Repetitive Voltage','*'),
	 ('Diode_Rectifier---Continuous_Forward_Current_Max_(A)','Maximum Continuous Forward Current','*'),
	 ('Diode_Rectifier---Peak_Reverse_Current_(uA)','Peak Reverse Current','*'),
	 ('Diode_Rectifier---Power_Dissipation_Max_(mW)','Maximum Power Dissipation','*'),
	 ('Diode_Rectifier---Junction_Ambient_Thermal_Resistance_Max','Maximum Junction Ambient Thermal Resistance',NULL),
	 ('Diode_Rectifier---Peak_Forward_Voltage_(V)','Peak Forward Voltage',NULL),
	 ('Diode_Rectifier---Configuration','Configuration',NULL),
	 ('Diode_Rectifier---Operating_Junction_Temperature_(C)','Operating Junction Temperature','*');
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('Diode_Rectifier---Type','Type','*'),
	 ('Diode_Zener---Type','Type',NULL),
	 ('Diode_Zener---Configuration','Configuration',NULL),
	 ('Diode_Zener---Nominal_Zener_Voltage_(V)','Nominal Zener Voltage','*'),
	 ('Diode_Zener---Zener_Impedance_Max_(R)','Maximum Zener Impedance',NULL),
	 ('Diode_Zener---Power_Dissipation_Max_(mW)','Maximum Power Dissipation','*'),
	 ('Diode_Zener---Reverse_Leakage_Current_Max_(uA)','Maximum Reverse Leakage Current','*'),
	 ('Diode_Zener---Junction_Ambient_Thermal_Resistance_Max','Maximum Junction Ambient Thermal Resistance',NULL),
	 ('Diode_Zener---Operating_Junction_Temperature_(C)','Operating Junction Temperature','*'),
	 ('Diode_Zener---Continuous_Forward_Current_Max','Maximum Continuous Forward Current','*');
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('Ferrite_Bead---Type','Type',NULL),
	 ('Ferrite_Bead---Test_Frequency_(Hz)','Test Frequency',NULL),
	 ('Ferrite_Bead---Impedance_(R)','Impedance','*'),
	 ('Ferrite_Bead---DC_Resistance_Max_(R)','Maximum DC Resistance','*'),
	 ('Ferrite_Bead---DC_Current_Max_(A)','Maximum DC Current','*'),
	 ('Ferrite_Bead---Tolerance','Tolerance','*'),
	 ('Fuse---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('Fuse---Package_Size','Package Size;Case Size;Size;Fuse Size',NULL),
	 ('Fuse---DC_Voltage_Rating_Max_(V)','Maximum DC Voltage Rating',NULL),
	 ('Fuse---Voltage_Rating_(V)','Voltage Rating','*');
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('Fuse---Typical_Cold_Resistance_(R)','Typical Cold Resistance',NULL),
	 ('Fuse---Current_Rating_(A)','Current Rating','*'),
	 ('Fuse---Typical_Melting_I2t_(A2s)','Typical Melting I2t','*'),
	 ('Fuse---Power_Dissipation_Max_(W)','Maximum Power Dissipation','*'),
	 ('Fuse---Type','Type',NULL),
	 ('Resettable_Fuse---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('Resettable_Fuse---Package_Size','Package Size;Case Size;Size',NULL),
	 ('Resettable_Fuse---Voltage_Rating_Max','Maximum Voltage Rating','*'),
	 ('Resettable_Fuse---Post_Trip_Resistance_Max_(R)','Maximum Post Trip Resistance','*'),
	 ('Resettable_Fuse---Initial_Resistance_Min_(R)','Minimum Initial Resistance',NULL);
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('Resettable_Fuse---Initial_Resistance_Max_(R)','Maximum Initial Resistance',NULL),
	 ('Resettable_Fuse---Hold_Current_(A)','Hold Current',NULL),
	 ('Resettable_Fuse---Trip_Current_(A)','Trip Current',NULL),
	 ('Resettable_Fuse---Current_Max_(A)','Maximum Current Rating','*'),
	 ('Resettable_Fuse---Trip_Time_Max_(s)','Maximum Trip Time',NULL),
	 ('Resettable_Fuse---Typical_Power_Dissipation_(W)','Typical Power Dissipation','*'),
	 ('Resettable_Fuse---Type','Type',NULL),
	 ('Transistor_BJT---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('Transistor_BJT---DC_Collector_Current_Max_(A)','Maximum DC Collector Current','*'),
	 ('Transistor_BJT---Collector_Emitter_Voltage_Max_(V)','Maximum Collector-Emitter Voltage','*');
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('Transistor_BJT---Collector_Base_Voltage_Max_(V)','Maximum Collector Base Voltage','*'),
	 ('Transistor_BJT---Emitter_Base_Voltage_Max_(V)','Maximum Emitter Base Voltage','*'),
	 ('Transistor_BJT---Base_Emitter_Saturation_Voltage_Max','Maximum Base Emitter Saturation Voltage',NULL),
	 ('Transistor_BJT---DC_current_gain_Min','Minimum DC Current Gain;DC current gain',NULL),
	 ('Transistor_BJT---Power_Dissipation_(mW)','Maximum Power Dissipation;Power Dissipation','*'),
	 ('Transistor_BJT---Typical_Power_Gain_(dB)','Typical Power Gain',NULL),
	 ('Transistor_BJT---Junction_Temperature_Max_(C)','Operating Junction Temperature','*'),
	 ('Transistor_BJT---Transition_Frequency_Max_(MHz)','Maximum Transition Frequency',NULL),
	 ('Transistor_BJT---Typical_Current_Gain_Bandwidth_(MHz)','Typical Current Gain Bandwidth',NULL),
	 ('Transistor_BJT---Junction_Ambient_Thermal_Resistance_Max','Maximum Junction Ambient Thermal Resistance',NULL);
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('Transistor_BJT---Junction_Case_Thermal_Resistance_Max','Maximum Junction Case Thermal Resistance',NULL),
	 ('Transistor_BJT---Type','Type',NULL),
	 ('Transistor_MOSFET---Drain_Source_Voltage_Max_(V)','Maximum Drain Source Voltage','*'),
	 ('Transistor_MOSFET---Gate_Source_Voltage_Max_(V)','Maximum Gate Source Voltage','*'),
	 ('Transistor_MOSFET---Continuous_Drain_Current_Max_(A)','Maximum Continuous Drain Current','*'),
	 ('Transistor_MOSFET---Reverse_Current_(uA)','Maximum IDSS',NULL),
	 ('Transistor_MOSFET---Power_Dissipation_Max_(mW)','Maximum Power Dissipation','*'),
	 ('Transistor_MOSFET---Typical_Gate_Charge_@_Vgs','Typical Gate Charge @ Vgs',NULL),
	 ('Transistor_MOSFET---Drain_Source_Resistance_Max_(mR)','Maximum Drain Source Resistance',NULL),
	 ('Transistor_MOSFET---Thermal_Resistance','Maximum Junction Ambient Thermal Resistance',NULL);
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('Transistor_MOSFET---Channel_Type','Channel Type','*'),
	 ('Transistor_MOSFET---Configuration','Configuration',NULL),
	 ('Transistor_MOSFET---Operating_Junction_Temperature_(C)','Operating Junction Temperature','*'),
	 ('Transistor_MOSFET---Junction_Ambient_Thermal_Resistance_Max','Maximum Junction Ambient Thermal Resistance',NULL),
	 ('Transistor_MOSFET---Junction_Case_Thermal_Resistance_Max','Maximum Junction Case Thermal Resistance',NULL),
	 ('IC_Audio_AMP---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('IC_Audio_AMP---Operating_Supply_Voltage_Max_(V)','Maximum Operating Supply Voltage','*'),
	 ('IC_Audio_AMP---Operating_Supply_Voltage_Min_(V)','Minimum Operating Supply Voltage',NULL),
	 ('IC_Audio_AMP---Operating_Junction_Temperature_(C)','Operating Junction Temperature','*'),
	 ('IC_Audio_AMP---Power_Dissipation_Max_(mW)','Maximum Power Dissipation',NULL);
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('IC_Audio_AMP---Function_Type','Type;Category;Logic Function;Interface Type',NULL),
	 ('IC_Buffer_Driver---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('IC_Buffer_Driver---Operating_Supply_Voltage_Max_(V)','Maximum Operating Supply Voltage','*'),
	 ('IC_Buffer_Driver---Operating_Supply_Voltage_Min_(V)','Minimum Operating Supply Voltage',NULL),
	 ('IC_Buffer_Driver---Operating_Junction_Temperature_(C)','Operating Junction Temperature','*'),
	 ('IC_Buffer_Driver---Power_Dissipation_Max_(mW)','Maximum Power Dissipation',NULL),
	 ('IC_Buffer_Driver---Function_Type','Type;Category;Logic Function;Interface Type',NULL),
	 ('IC_Bus_Switch---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('IC_Bus_Switch---Operating_Supply_Voltage_Max_(V)','Maximum Operating Supply Voltage','*'),
	 ('IC_Bus_Switch---Operating_Supply_Voltage_Min_(V)','Minimum Operating Supply Voltage',NULL);
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('IC_Bus_Switch---Operating_Junction_Temperature_(C)','Operating Junction Temperature','*'),
	 ('IC_Bus_Switch---Power_Dissipation_Max_(mW)','Maximum Power Dissipation',NULL),
	 ('IC_Bus_Switch---Function_Type','Type;Category;Logic Function;Interface Type',NULL),
	 ('IC_Bus_Switch---Number_of_Channels','Number of Channels;Number of Channels per Chip;Number of Elements per Chip',NULL),
	 ('IC_Bus_Switch---Interface_Type','Interface Type;Process Technology',NULL),
	 ('IC_Circuit_Protection---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('IC_Circuit_Protection---Operating_Supply_Voltage_Max_(V)','Maximum Operating Supply Voltage','*'),
	 ('IC_Circuit_Protection---Operating_Supply_Voltage_Min_(V)','Minimum Operating Supply Voltage',NULL),
	 ('IC_Circuit_Protection---Operating_Junction_Temperature_(C)','Operating Junction Temperature','*'),
	 ('IC_Circuit_Protection---Power_Dissipation_Max_(mW)','Maximum Power Dissipation',NULL);
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('IC_Circuit_Protection---Function_Type','Type;Category;Logic Function;Interface Type',NULL),
	 ('IC_Circuit_Protection---Supply_Current_Max','Maximum Supply Current',NULL),
	 ('IC_Clock_Buffer---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('IC_Clock_Buffer---Operating_Supply_Voltage_Max_(V)','Maximum Operating Supply Voltage','*'),
	 ('IC_Clock_Buffer---Operating_Supply_Voltage_Min_(V)','Minimum Operating Supply Voltage',NULL),
	 ('IC_Clock_Buffer---Operating_Junction_Temperature_(C)','Operating Junction Temperature','*'),
	 ('IC_Clock_Buffer---Power_Dissipation_Max_(mW)','Maximum Power Dissipation',NULL),
	 ('IC_Clock_Buffer---Function_Type','Type;Category;Logic Function;Interface Type',NULL),
	 ('IC_Clock_Distribution---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('IC_Clock_Distribution---Operating_Supply_Voltage_Max_(V)','Maximum Operating Supply Voltage','*');
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('IC_Clock_Distribution---Operating_Supply_Voltage_Min_(V)','Minimum Operating Supply Voltage',NULL),
	 ('IC_Clock_Distribution---Operating_Junction_Temperature_(C)','Operating Junction Temperature','*'),
	 ('IC_Clock_Distribution---Power_Dissipation_Max_(mW)','Maximum Power Dissipation',NULL),
	 ('IC_Clock_Distribution---Function_Type','Type;Category;Logic Function;Interface Type',NULL),
	 ('IC_Comparator---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('IC_Comparator---Operating_Supply_Voltage_Max_(V)','Maximum Operating Supply Voltage','*'),
	 ('IC_Comparator---Operating_Supply_Voltage_Min_(V)','Minimum Operating Supply Voltage',NULL),
	 ('IC_Comparator---Operating_Junction_Temperature_(C)','Operating Junction Temperature','*'),
	 ('IC_Comparator---Power_Dissipation_Max_(mW)','Maximum Power Dissipation',NULL),
	 ('IC_Comparator---Function_Type','Type;Category;Logic Function;Interface Type',NULL);
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('IC_CPLD---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('IC_CPLD---Operating_Supply_Voltage_Max_(V)','Maximum Operating Supply Voltage','*'),
	 ('IC_CPLD---Operating_Supply_Voltage_Min_(V)','Minimum Operating Supply Voltage',NULL),
	 ('IC_CPLD---Operating_Junction_Temperature_(C)','Operating Junction Temperature','*'),
	 ('IC_CPLD---Power_Dissipation_Max_(mW)','Maximum Power Dissipation',NULL),
	 ('IC_CPLD---Function_Type','Type;Category;Logic Function;Interface Type',NULL),
	 ('IC_CPU---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('IC_CPU---Operating_Supply_Voltage_Max_(V)','Maximum Operating Supply Voltage','*'),
	 ('IC_CPU---Operating_Supply_Voltage_Min_(V)','Minimum Operating Supply Voltage',NULL),
	 ('IC_CPU---Operating_Junction_Temperature_(C)','Operating Junction Temperature','*');
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('IC_CPU---Power_Dissipation_Max_(mW)','Maximum Power Dissipation',NULL),
	 ('IC_CPU---Function_Type','Type;Category;Logic Function;Interface Type',NULL),
	 ('IC_CPU---Number_of_Cores','Core;Number of CPU Cores;Total Cores;Device Core',NULL),
	 ('IC_CPU---Device_Core','Device Core',NULL),
	 ('IC_Chipset---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('IC_Chipset---Operating_Supply_Voltage_Max_(V)','Maximum Operating Supply Voltage','*'),
	 ('IC_Chipset---Operating_Supply_Voltage_Min_(V)','Minimum Operating Supply Voltage',NULL),
	 ('IC_Chipset---Operating_Junction_Temperature_(C)','Operating Junction Temperature','*'),
	 ('IC_Chipset---Power_Dissipation_Max_(mW)','Maximum Power Dissipation',NULL),
	 ('IC_Chipset---Function_Type','Type;Category;Logic Function;Interface Type',NULL);
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('IC_Chipset---Code_Name','Code Name',NULL),
	 ('IC_DA_AD_Converter---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('IC_DA_AD_Converter---Operating_Supply_Voltage_Max_(V)','Maximum Operating Supply Voltage','*'),
	 ('IC_DA_AD_Converter---Operating_Supply_Voltage_Min_(V)','Minimum Operating Supply Voltage',NULL),
	 ('IC_DA_AD_Converter---Operating_Junction_Temperature_(C)','Operating Junction Temperature','*'),
	 ('IC_DA_AD_Converter---Power_Dissipation_Max_(mW)','Maximum Power Dissipation',NULL),
	 ('IC_DA_AD_Converter---Function_Type','Type;Category;Logic Function;Interface Type',NULL),
	 ('IC_DA_AD_Converter---Supply_Current_Max','Maximum Supply Current','*'),
	 ('IC_DC_to_DC_Controller---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('IC_DC_to_DC_Controller---Operating_Supply_Voltage_Max_(V)','Maximum Operating Supply Voltage','*');
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('IC_DC_to_DC_Controller---Operating_Supply_Voltage_Min_(V)','Minimum Operating Supply Voltage',NULL),
	 ('IC_DC_to_DC_Controller---Operating_Junction_Temperature_(C)','Operating Junction Temperature','*'),
	 ('IC_DC_to_DC_Controller---Power_Dissipation_Max_(mW)','Maximum Power Dissipation',NULL),
	 ('IC_DC_to_DC_Controller---Function_Type','Type;Category;Logic Function;Interface Type',NULL),
	 ('IC_DC_to_DC_Conversion---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('IC_DC_to_DC_Conversion---Operating_Supply_Voltage_Max_(V)','Maximum Operating Supply Voltage','*'),
	 ('IC_DC_to_DC_Conversion---Operating_Supply_Voltage_Min_(V)','Minimum Operating Supply Voltage',NULL),
	 ('IC_DC_to_DC_Conversion---Operating_Junction_Temperature_(C)','Operating Junction Temperature','*'),
	 ('IC_DC_to_DC_Conversion---Power_Dissipation_Max_(mW)','Maximum Power Dissipation',NULL),
	 ('IC_DC_to_DC_Conversion---Function_Type','Type;Category;Logic Function;Interface Type',NULL);
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('IC_DC_to_DC_Conversion---Output_Current_Max','Maximum Output Current',NULL),
	 ('IC_DRAM---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('IC_DRAM---Operating_Supply_Voltage_Max_(V)','Maximum Operating Supply Voltage','*'),
	 ('IC_DRAM---Operating_Supply_Voltage_Min_(V)','Minimum Operating Supply Voltage',NULL),
	 ('IC_DRAM---Operating_Junction_Temperature_(C)','Operating Junction Temperature','*'),
	 ('IC_DRAM---Power_Dissipation_Max_(mW)','Maximum Power Dissipation',NULL),
	 ('IC_DRAM---Function_Type','Type;Category;Logic Function;Interface Type',NULL),
	 ('IC_DRAM---Memory_Type','Memory Type',NULL),
	 ('IC_EEPROM---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('IC_EEPROM---Operating_Supply_Voltage_Max_(V)','Maximum Operating Supply Voltage','*');
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('IC_EEPROM---Operating_Supply_Voltage_Min_(V)','Minimum Operating Supply Voltage',NULL),
	 ('IC_EEPROM---Operating_Junction_Temperature_(C)','Operating Junction Temperature','*'),
	 ('IC_EEPROM---Power_Dissipation_Max_(mW)','Maximum Power Dissipation',NULL),
	 ('IC_EEPROM---Function_Type','Type;Category;Logic Function;Interface Type',NULL),
	 ('IC_EEPROM---Interface_Type','Interface Type;Process Technology',NULL),
	 ('IC_Ethernet---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('IC_Ethernet---Operating_Supply_Voltage_Max_(V)','Maximum Operating Supply Voltage','*'),
	 ('IC_Ethernet---Operating_Supply_Voltage_Min_(V)','Minimum Operating Supply Voltage',NULL),
	 ('IC_Ethernet---Operating_Junction_Temperature_(C)','Operating Junction Temperature','*'),
	 ('IC_Ethernet---Power_Dissipation_Max_(mW)','Maximum Power Dissipation',NULL);
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('IC_Ethernet---Function_Type','Type;Category;Logic Function;Interface Type',NULL),
	 ('IC_Ethernet---Interface_Type','Interface Type;Process Technology',NULL),
	 ('IC_Ethernet_PHY---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('IC_Ethernet_PHY---Operating_Supply_Voltage_Max_(V)','Maximum Operating Supply Voltage','*'),
	 ('IC_Ethernet_PHY---Operating_Supply_Voltage_Min_(V)','Minimum Operating Supply Voltage',NULL),
	 ('IC_Ethernet_PHY---Operating_Junction_Temperature_(C)','Operating Junction Temperature','*'),
	 ('IC_Ethernet_PHY---Power_Dissipation_Max_(mW)','Maximum Power Dissipation',NULL),
	 ('IC_Ethernet_PHY---Function_Type','Type;Category;Logic Function;Interface Type',NULL),
	 ('IC_Ethernet_PHY---Interface_Type','Interface Type;Process Technology',NULL),
	 ('IC_Flash---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*');
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('IC_Flash---Operating_Supply_Voltage_Max_(V)','Maximum Operating Supply Voltage','*'),
	 ('IC_Flash---Operating_Supply_Voltage_Min_(V)','Minimum Operating Supply Voltage',NULL),
	 ('IC_Flash---Operating_Junction_Temperature_(C)','Operating Junction Temperature','*'),
	 ('IC_Flash---Power_Dissipation_Max_(mW)','Maximum Power Dissipation',NULL),
	 ('IC_Flash---Function_Type','Type;Category;Logic Function;Interface Type',NULL),
	 ('IC_Flash---Interface_Type','Interface Type;Process Technology',NULL),
	 ('IC_FlipFlop---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('IC_FlipFlop---Operating_Supply_Voltage_Max_(V)','Maximum Operating Supply Voltage','*'),
	 ('IC_FlipFlop---Operating_Supply_Voltage_Min_(V)','Minimum Operating Supply Voltage',NULL),
	 ('IC_FlipFlop---Operating_Junction_Temperature_(C)','Operating Junction Temperature','*');
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('IC_FlipFlop---Power_Dissipation_Max_(mW)','Maximum Power Dissipation',NULL),
	 ('IC_FlipFlop---Function_Type','Type;Category;Logic Function;Interface Type',NULL),
	 ('IC_FPGA---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('IC_FPGA---Operating_Supply_Voltage_Max_(V)','Maximum Operating Supply Voltage','*'),
	 ('IC_FPGA---Operating_Supply_Voltage_Min_(V)','Minimum Operating Supply Voltage',NULL),
	 ('IC_FPGA---Operating_Junction_Temperature_(C)','Operating Junction Temperature','*'),
	 ('IC_FPGA---Power_Dissipation_Max_(mW)','Maximum Power Dissipation',NULL),
	 ('IC_FPGA---Function_Type','Type;Category;Logic Function;Interface Type',NULL),
	 ('IC_FRAM---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('IC_FRAM---Operating_Supply_Voltage_Max_(V)','Maximum Operating Supply Voltage','*');
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('IC_FRAM---Operating_Supply_Voltage_Min_(V)','Minimum Operating Supply Voltage',NULL),
	 ('IC_FRAM---Operating_Junction_Temperature_(C)','Operating Junction Temperature','*'),
	 ('IC_FRAM---Power_Dissipation_Max_(mW)','Maximum Power Dissipation',NULL),
	 ('IC_FRAM---Function_Type','Type;Category;Logic Function;Interface Type',NULL),
	 ('IC_FRAM---Interface_Type','Interface Type;Process Technology',NULL),
	 ('IC_Gate---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('IC_Gate---Operating_Supply_Voltage_Max_(V)','Maximum Operating Supply Voltage','*'),
	 ('IC_Gate---Operating_Supply_Voltage_Min_(V)','Minimum Operating Supply Voltage',NULL),
	 ('IC_Gate---Operating_Junction_Temperature_(C)','Operating Junction Temperature','*'),
	 ('IC_Gate---Power_Dissipation_Max_(mW)','Maximum Power Dissipation',NULL);
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('IC_Gate---Function_Type','Type;Category;Logic Function;Interface Type',NULL),
	 ('IC_Hot_Swap---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('IC_Hot_Swap---Operating_Supply_Voltage_Max_(V)','Maximum Operating Supply Voltage','*'),
	 ('IC_Hot_Swap---Operating_Supply_Voltage_Min_(V)','Minimum Operating Supply Voltage',NULL),
	 ('IC_Hot_Swap---Operating_Junction_Temperature_(C)','Operating Junction Temperature','*'),
	 ('IC_Hot_Swap---Power_Dissipation_Max_(mW)','Maximum Power Dissipation',NULL),
	 ('IC_Hot_Swap---Function_Type','Type;Category;Logic Function;Interface Type',NULL),
	 ('IC_IO_Controller---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('IC_IO_Controller---Operating_Supply_Voltage_Max_(V)','Maximum Operating Supply Voltage','*'),
	 ('IC_IO_Controller---Operating_Supply_Voltage_Min_(V)','Minimum Operating Supply Voltage',NULL);
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('IC_IO_Controller---Operating_Junction_Temperature_(C)','Operating Junction Temperature','*'),
	 ('IC_IO_Controller---Power_Dissipation_Max_(mW)','Maximum Power Dissipation',NULL),
	 ('IC_IO_Controller---Function_Type','Type;Category;Logic Function;Interface Type',NULL),
	 ('IC_IO_Controller---Interface_Type','Interface Type;Process Technology',NULL),
	 ('IC_Inverter_and_Triggers---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('IC_Inverter_and_Triggers---Operating_Supply_Voltage_Max_(V)','Maximum Operating Supply Voltage','*'),
	 ('IC_Inverter_and_Triggers---Operating_Supply_Voltage_Min_(V)','Minimum Operating Supply Voltage',NULL),
	 ('IC_Inverter_and_Triggers---Operating_Junction_Temperature_(C)','Operating Junction Temperature','*'),
	 ('IC_Inverter_and_Triggers---Power_Dissipation_Max_(mW)','Maximum Power Dissipation',NULL),
	 ('IC_Inverter_and_Triggers---Function_Type','Type;Category;Logic Function;Interface Type',NULL);
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('IC_LCD_Driver---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('IC_LCD_Driver---Operating_Supply_Voltage_Max_(V)','Maximum Operating Supply Voltage','*'),
	 ('IC_LCD_Driver---Operating_Supply_Voltage_Min_(V)','Minimum Operating Supply Voltage',NULL),
	 ('IC_LCD_Driver---Operating_Junction_Temperature_(C)','Operating Junction Temperature','*'),
	 ('IC_LCD_Driver---Power_Dissipation_Max_(mW)','Maximum Power Dissipation',NULL),
	 ('IC_LCD_Driver---Function_Type','Type;Category;Logic Function;Interface Type',NULL),
	 ('IC_LED_Driver---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('IC_LED_Driver---Operating_Supply_Voltage_Max_(V)','Maximum Operating Supply Voltage','*'),
	 ('IC_LED_Driver---Operating_Supply_Voltage_Min_(V)','Minimum Operating Supply Voltage',NULL),
	 ('IC_LED_Driver---Operating_Junction_Temperature_(C)','Operating Junction Temperature','*');
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('IC_LED_Driver---Power_Dissipation_Max_(mW)','Maximum Power Dissipation',NULL),
	 ('IC_LED_Driver---Function_Type','Type;Category;Logic Function;Interface Type',NULL),
	 ('IC_MCU---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('IC_MCU---Operating_Supply_Voltage_Max_(V)','Maximum Operating Supply Voltage','*'),
	 ('IC_MCU---Operating_Supply_Voltage_Min_(V)','Minimum Operating Supply Voltage',NULL),
	 ('IC_MCU---Operating_Junction_Temperature_(C)','Operating Junction Temperature','*'),
	 ('IC_MCU---Power_Dissipation_Max_(mW)','Maximum Power Dissipation',NULL),
	 ('IC_MCU---Function_Type','Type;Category;Logic Function;Interface Type',NULL),
	 ('IC_MCU---Device_Core','Device Core',NULL),
	 ('IC_Motor_Driver---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*');
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('IC_Motor_Driver---Operating_Supply_Voltage_Max_(V)','Maximum Operating Supply Voltage','*'),
	 ('IC_Motor_Driver---Operating_Supply_Voltage_Min_(V)','Minimum Operating Supply Voltage',NULL),
	 ('IC_Motor_Driver---Operating_Junction_Temperature_(C)','Operating Junction Temperature','*'),
	 ('IC_Motor_Driver---Power_Dissipation_Max_(mW)','Maximum Power Dissipation',NULL),
	 ('IC_Motor_Driver---Function_Type','Type;Category;Logic Function;Interface Type',NULL),
	 ('IC_Multimedia_Converter---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('IC_Multimedia_Converter---Operating_Supply_Voltage_Max_(V)','Maximum Operating Supply Voltage','*'),
	 ('IC_Multimedia_Converter---Operating_Supply_Voltage_Min_(V)','Minimum Operating Supply Voltage',NULL),
	 ('IC_Multimedia_Converter---Operating_Junction_Temperature_(C)','Operating Junction Temperature','*'),
	 ('IC_Multimedia_Converter---Power_Dissipation_Max_(mW)','Maximum Power Dissipation',NULL);
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('IC_Multimedia_Converter---Function_Type','Type;Category;Logic Function;Interface Type',NULL),
	 ('IC_Multivibrator---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('IC_Multivibrator---Operating_Supply_Voltage_Max_(V)','Maximum Operating Supply Voltage','*'),
	 ('IC_Multivibrator---Operating_Supply_Voltage_Min_(V)','Minimum Operating Supply Voltage',NULL),
	 ('IC_Multivibrator---Operating_Junction_Temperature_(C)','Operating Junction Temperature','*'),
	 ('IC_Multivibrator---Power_Dissipation_Max_(mW)','Maximum Power Dissipation',NULL),
	 ('IC_Multivibrator---Function_Type','Type;Category;Logic Function;Interface Type',NULL),
	 ('IC_OP_AMP---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('IC_OP_AMP---Operating_Supply_Voltage_Max_(V)','Maximum Operating Supply Voltage','*'),
	 ('IC_OP_AMP---Operating_Supply_Voltage_Min_(V)','Minimum Operating Supply Voltage',NULL);
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('IC_OP_AMP---Operating_Junction_Temperature_(C)','Operating Junction Temperature','*'),
	 ('IC_OP_AMP---Power_Dissipation_Max_(mW)','Maximum Power Dissipation',NULL),
	 ('IC_OP_AMP---Function_Type','Type;Category;Logic Function;Interface Type',NULL),
	 ('IC_PMIC---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('IC_PMIC---Operating_Supply_Voltage_Max_(V)','Maximum Operating Supply Voltage','*'),
	 ('IC_PMIC---Operating_Supply_Voltage_Min_(V)','Minimum Operating Supply Voltage',NULL),
	 ('IC_PMIC---Operating_Junction_Temperature_(C)','Operating Junction Temperature','*'),
	 ('IC_PMIC---Power_Dissipation_Max_(mW)','Maximum Power Dissipation',NULL),
	 ('IC_PMIC---Function_Type','Type;Category;Logic Function;Interface Type',NULL),
	 ('IC_Power_Driver---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*');
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('IC_Power_Driver---Operating_Supply_Voltage_Max_(V)','Maximum Operating Supply Voltage','*'),
	 ('IC_Power_Driver---Operating_Supply_Voltage_Min_(V)','Minimum Operating Supply Voltage',NULL),
	 ('IC_Power_Driver---Operating_Junction_Temperature_(C)','Operating Junction Temperature','*'),
	 ('IC_Power_Driver---Power_Dissipation_Max_(mW)','Maximum Power Dissipation',NULL),
	 ('IC_Power_Driver---Function_Type','Type;Category;Logic Function;Interface Type',NULL),
	 ('IC_Power_Supply---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('IC_Power_Supply---Operating_Supply_Voltage_Max_(V)','Maximum Operating Supply Voltage','*'),
	 ('IC_Power_Supply---Operating_Supply_Voltage_Min_(V)','Minimum Operating Supply Voltage',NULL),
	 ('IC_Power_Supply---Operating_Junction_Temperature_(C)','Operating Junction Temperature','*'),
	 ('IC_Power_Supply---Power_Dissipation_Max_(mW)','Maximum Power Dissipation',NULL);
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('IC_Power_Supply---Function_Type','Type;Category;Logic Function;Interface Type',NULL),
	 ('IC_Power_Switch---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('IC_Power_Switch---Operating_Supply_Voltage_Max_(V)','Maximum Operating Supply Voltage','*'),
	 ('IC_Power_Switch---Operating_Supply_Voltage_Min_(V)','Minimum Operating Supply Voltage',NULL),
	 ('IC_Power_Switch---Operating_Junction_Temperature_(C)','Operating Junction Temperature','*'),
	 ('IC_Power_Switch---Power_Dissipation_Max_(mW)','Maximum Power Dissipation',NULL),
	 ('IC_Power_Switch---Function_Type','Type;Category;Logic Function;Interface Type',NULL),
	 ('IC_Power_Switch---Supply_Current_(mA)','Supply Current',NULL),
	 ('IC_Power_Switch---Output_Current_Min_(A)','Minimum Output Current',NULL),
	 ('IC_Power_Switch---Switch_On_Resistance_(R)','Switch On Resistance',NULL);
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('IC_Security---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('IC_Security---Operating_Supply_Voltage_Max_(V)','Maximum Operating Supply Voltage','*'),
	 ('IC_Security---Operating_Supply_Voltage_Min_(V)','Minimum Operating Supply Voltage',NULL),
	 ('IC_Security---Operating_Junction_Temperature_(C)','Operating Junction Temperature','*'),
	 ('IC_Security---Power_Dissipation_Max_(mW)','Maximum Power Dissipation',NULL),
	 ('IC_Security---Function_Type','Type;Category;Logic Function;Interface Type',NULL),
	 ('IC_Sensor---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('IC_Sensor---Operating_Supply_Voltage_Max_(V)','Maximum Operating Supply Voltage','*'),
	 ('IC_Sensor---Operating_Supply_Voltage_Min_(V)','Minimum Operating Supply Voltage',NULL),
	 ('IC_Sensor---Operating_Junction_Temperature_(C)','Operating Junction Temperature','*');
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('IC_Sensor---Power_Dissipation_Max_(mW)','Maximum Power Dissipation',NULL),
	 ('IC_Sensor---Function_Type','Type;Category;Logic Function;Interface Type',NULL),
	 ('IC_Shifter---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('IC_Shifter---Operating_Supply_Voltage_Max_(V)','Maximum Operating Supply Voltage','*'),
	 ('IC_Shifter---Operating_Supply_Voltage_Min_(V)','Minimum Operating Supply Voltage',NULL),
	 ('IC_Shifter---Operating_Junction_Temperature_(C)','Operating Junction Temperature','*'),
	 ('IC_Shifter---Power_Dissipation_Max_(mW)','Maximum Power Dissipation',NULL),
	 ('IC_Shifter---Function_Type','Type;Category;Logic Function;Interface Type',NULL),
	 ('IC_Supervisory_Circuit---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('IC_Supervisory_Circuit---Operating_Supply_Voltage_Max_(V)','Maximum Operating Supply Voltage','*');
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('IC_Supervisory_Circuit---Operating_Supply_Voltage_Min_(V)','Minimum Operating Supply Voltage',NULL),
	 ('IC_Supervisory_Circuit---Operating_Junction_Temperature_(C)','Operating Junction Temperature','*'),
	 ('IC_Supervisory_Circuit---Power_Dissipation_Max_(mW)','Maximum Power Dissipation',NULL),
	 ('IC_Supervisory_Circuit---Function_Type','Type;Category;Logic Function;Interface Type',NULL),
	 ('IC_Switch_Multiplexer---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('IC_Switch_Multiplexer---Operating_Supply_Voltage_Max_(V)','Maximum Operating Supply Voltage','*'),
	 ('IC_Switch_Multiplexer---Operating_Supply_Voltage_Min_(V)','Minimum Operating Supply Voltage',NULL),
	 ('IC_Switch_Multiplexer---Operating_Junction_Temperature_(C)','Operating Junction Temperature','*'),
	 ('IC_Switch_Multiplexer---Power_Dissipation_Max_(mW)','Maximum Power Dissipation',NULL),
	 ('IC_Switch_Multiplexer---Function_Type','Type;Category;Logic Function;Interface Type',NULL);
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('IC_Switch_Multiplexer---Interface_Type','Interface Type;Process Technology',NULL),
	 ('IC_Temperature_Sensor---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('IC_Temperature_Sensor---Operating_Supply_Voltage_Max_(V)','Maximum Operating Supply Voltage','*'),
	 ('IC_Temperature_Sensor---Operating_Supply_Voltage_Min_(V)','Minimum Operating Supply Voltage',NULL),
	 ('IC_Temperature_Sensor---Operating_Junction_Temperature_(C)','Operating Junction Temperature','*'),
	 ('IC_Temperature_Sensor---Power_Dissipation_Max_(mW)','Maximum Power Dissipation',NULL),
	 ('IC_Temperature_Sensor---Function_Type','Type;Category;Logic Function;Interface Type',NULL),
	 ('IC_Transceiver---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('IC_Transceiver---Operating_Supply_Voltage_Max_(V)','Maximum Operating Supply Voltage','*'),
	 ('IC_Transceiver---Operating_Supply_Voltage_Min_(V)','Minimum Operating Supply Voltage',NULL);
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('IC_Transceiver---Operating_Junction_Temperature_(C)','Operating Junction Temperature','*'),
	 ('IC_Transceiver---Power_Dissipation_Max_(mW)','Maximum Power Dissipation',NULL),
	 ('IC_Transceiver---Function_Type','Type;Category;Logic Function;Interface Type',NULL),
	 ('IC_Interface_CODEC---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('IC_Interface_CODEC---Operating_Supply_Voltage_Max_(V)','Maximum Operating Supply Voltage','*'),
	 ('IC_Interface_CODEC---Operating_Supply_Voltage_Min_(V)','Minimum Operating Supply Voltage',NULL),
	 ('IC_Interface_CODEC---Operating_Junction_Temperature_(C)','Operating Junction Temperature','*'),
	 ('IC_Interface_CODEC---Power_Dissipation_Max_(mW)','Maximum Power Dissipation',NULL),
	 ('IC_Interface_CODEC---Function_Type','Type;Category;Logic Function;Interface Type',NULL),
	 ('IC_Interface_CODEC---Interface_Type','Interface Type;Process Technology',NULL);
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('IC_Interface_IO_Expander---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('IC_Interface_IO_Expander---Operating_Supply_Voltage_Max_(V)','Maximum Operating Supply Voltage','*'),
	 ('IC_Interface_IO_Expander---Operating_Supply_Voltage_Min_(V)','Minimum Operating Supply Voltage',NULL),
	 ('IC_Interface_IO_Expander---Operating_Junction_Temperature_(C)','Operating Junction Temperature','*'),
	 ('IC_Interface_IO_Expander---Power_Dissipation_Max_(mW)','Maximum Power Dissipation',NULL),
	 ('IC_Interface_IO_Expander---Function_Type','Type;Category;Logic Function;Interface Type',NULL),
	 ('IC_Interface_IO_Expander---Interface_Type','Interface Type;Process Technology',NULL),
	 ('IC_Interface_LVDS---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('IC_Interface_LVDS---Operating_Supply_Voltage_Max_(V)','Maximum Operating Supply Voltage','*'),
	 ('IC_Interface_LVDS---Operating_Supply_Voltage_Min_(V)','Minimum Operating Supply Voltage',NULL);
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('IC_Interface_LVDS---Operating_Junction_Temperature_(C)','Operating Junction Temperature','*'),
	 ('IC_Interface_LVDS---Power_Dissipation_Max_(mW)','Maximum Power Dissipation',NULL),
	 ('IC_Interface_LVDS---Function_Type','Type;Category;Logic Function;Interface Type',NULL),
	 ('IC_Interface_UART---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('IC_Interface_UART---Operating_Supply_Voltage_Max_(V)','Maximum Operating Supply Voltage','*'),
	 ('IC_Interface_UART---Operating_Supply_Voltage_Min_(V)','Minimum Operating Supply Voltage',NULL),
	 ('IC_Interface_UART---Operating_Junction_Temperature_(C)','Operating Junction Temperature','*'),
	 ('IC_Interface_UART---Power_Dissipation_Max_(mW)','Maximum Power Dissipation',NULL),
	 ('IC_Interface_UART---Function_Type','Type;Category;Logic Function;Interface Type',NULL),
	 ('IC_Interface_USB---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*');
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('IC_Interface_USB---Operating_Supply_Voltage_Max_(V)','Maximum Operating Supply Voltage','*'),
	 ('IC_Interface_USB---Operating_Supply_Voltage_Min_(V)','Minimum Operating Supply Voltage',NULL),
	 ('IC_Interface_USB---Operating_Junction_Temperature_(C)','Operating Junction Temperature','*'),
	 ('IC_Interface_USB---Power_Dissipation_Max_(mW)','Maximum Power Dissipation',NULL),
	 ('IC_Interface_USB---Function_Type','Type;Category;Logic Function;Interface Type',NULL),
	 ('IC_Voltage_Regulator---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('IC_Voltage_Regulator---Operating_Supply_Voltage_Max_(V)','Maximum Operating Supply Voltage','*'),
	 ('IC_Voltage_Regulator---Operating_Supply_Voltage_Min_(V)','Minimum Operating Supply Voltage',NULL),
	 ('IC_Voltage_Regulator---Operating_Junction_Temperature_(C)','Operating Junction Temperature','*'),
	 ('IC_Voltage_Regulator---Power_Dissipation_Max_(mW)','Maximum Power Dissipation',NULL);
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('IC_Voltage_Regulator---Function_Type','Type;Category;Logic Function;Interface Type',NULL),
	 ('IC_Voltage_Regulator---Output_Current_(A)','Output Current','*'),
	 ('LED---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('LED---Number_of_LEDS','Number of LEDs','*'),
	 ('LED---Type','Type',NULL),
	 ('LED---Emitted_Color','Emitted Color;Color','*'),
	 ('LED---Lens_Color','Lens Color;Lens Appearance',NULL),
	 ('LED---Peak_Wavelength_(nm)','Peak Wavelength',NULL),
	 ('LED---Peak_Wavelength_Range_(nm)','Peak Wavelength Range',NULL),
	 ('LED---Peak_Dominant_Wavelength_(nm)','Dominant Wavelength',NULL);
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('LED---Forward_Voltage_Max_(V)','Maximum Forward Voltage',NULL),
	 ('LED---Forward_Voltage_Range_Max_(V)','Maximum Forward Voltage Range',NULL),
	 ('LED---Forward_Current_Max_(mA)','Maximum Forward Current','*'),
	 ('LED---Reverse_Voltage_(V)','Reverse Voltage','*'),
	 ('LED---Reverse_Current_Max_(uA)','Maximum Reverse Current','*'),
	 ('LED---Power_Dissipation_Max_(mW)','Maximum Power Dissipation','*'),
	 ('LED---Luminous_Intensity','Luminous Intensity;Intensity',NULL),
	 ('LED---Package_Diameter','Package Diameter','*'),
	 ('LED---Operating_Junction_Temperature_(C)','Operating Junction Temperature',NULL),
	 ('LED---Junction_Ambient_Thermal_Resistance_Max','Maximum Junction Ambient Thermal Resistance',NULL);
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('LED---Leakage_Current_(uA)','Leakage Current',NULL),
	 ('LED_Display---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('LED_Display---Number_of_LED','Number of LEDs','*'),
	 ('LED_Display---Type','Type',NULL),
	 ('LED_Display---Color','Color;Emitted Color','*'),
	 ('LED_Display---Peak_Wavelength_(nm)','Peak Wavelength',NULL),
	 ('LED_Display---Dominant_Wavelength_(nm)','Dominant Wavelength',NULL),
	 ('LED_Display---Forward_Voltage_Max_(V)','Maximum Forward Voltage','*'),
	 ('LED_Display---Forward_Current_Max_(mA)','Maximum Forward Current','*'),
	 ('LED_Display---Reverse_Voltage_Max_(V)','Maximum Reverse Voltage','*');
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('LED_Display---Reverse_Current_Max_(uA)','Maximum Reverse Current','*'),
	 ('LED_Display---Power_Dissipation_Max_(mW)','Maximum Power Dissipation','*'),
	 ('LED_Display---Intensity_(ucd)','Luminous Intensity;Intensity',NULL),
	 ('LED_Display---Package_Diameter','Package Diameter',NULL),
	 ('Power_Inductor---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('Power_Inductor---Technology','Technology',NULL),
	 ('Power_Inductor---Inductance_(H)','Inductance','*'),
	 ('Power_Inductor---Tolerance','Tolerance','*'),
	 ('Power_Inductor---Saturation_Current_Max_(A)','Maximum Saturation Current',NULL),
	 ('Power_Inductor---DC_Resistance_Max_(R)','Maximum DC Resistance','*');
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('Power_Inductor---Test_Frequency_(Hz)','Inductance Test Frequency',NULL),
	 ('Power_Inductor---Self_Resonant_Frequency_Min_(Hz)','Minimum Self Resonant Frequency',NULL),
	 ('Power_Inductor---Quality_Factor_Min_(Hz)','Minimum Quality Factor',NULL),
	 ('Power_Inductor---DC_Current_Max_(A)','Maximum DC Current','*'),
	 ('Power_Inductor---Type','Type',NULL),
	 ('RF_Inductor---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('RF_Inductor---Technology','Technology',NULL),
	 ('RF_Inductor---Test_Frequency_(Hz)','Inductance Test Frequency','*'),
	 ('RF_Inductor---Quality_Test_Frequency_(Hz)','Quality Test Frequency',NULL),
	 ('RF_Inductor---Inductance_(H)','Inductance','*');
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('RF_Inductor---Tolerance','Tolerance','*'),
	 ('RF_Inductor---Saturation_Current_Max_(A)','Maximum Saturation Current',NULL),
	 ('RF_Inductor---DC_Resistance_Max_(R)','Maximum DC Resistance','*'),
	 ('RF_Inductor---Quality_Factor_Min','Minimum Quality Factor',NULL),
	 ('RF_Inductor---Self_Resonant_Frequency_Min_(Hz)','Minimum Self Resonant Frequency',NULL),
	 ('RF_Inductor---DC_Current_Max_(A)','Maximum DC Current','*'),
	 ('RF_Inductor---Type','Type',NULL),
	 ('Resistor_Thin_Thick---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('Resistor_Thin_Thick---Package_Size','Package Size;Case Size;Size','*'),
	 ('Resistor_Thin_Thick---Device_Type','Technology;Device Type;Construction;Case Style;','*');
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('Resistor_Thin_Thick---Resistance_(R)','Resistance;Resistance Value','*'),
	 ('Resistor_Thin_Thick---Resistance_UnitedValue','Resistance Value UnitedValue','*'),
	 ('Resistor_Thin_Thick---Resistance_UnitedUnit','Resistance Value UnitedUnit','*'),
	 ('Resistor_Thin_Thick---Tolerance','Tolerance','*'),
	 ('Resistor_Thin_Thick---Rated_Power_(W)','Power Rating','*'),
	 ('Resistor_Thin_Thick---Voltage_Rating_Max_(V)','Maximum Voltage Rating','*'),
	 ('Resistor_Thin_Thick---Current_Sensing','Current Sensing','*'),
	 ('Resistor_Thin_Thick---Maximum_Current_Rating_(A)','Maximum Current Rating',NULL),
	 ('Resistor_Thin_Thick---Temperature_Coefficient_(ppm/C)','Temperature Coefficient','*'),
	 ('Resistor_Networks_and_Array---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*');
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('Resistor_Networks_and_Array---Package_Size','Package Size;Case Size;Size','*'),
	 ('Resistor_Networks_and_Array---Device_Type','Technology;Device Type;Construction;Case Style;',NULL),
	 ('Resistor_Networks_and_Array---Resistance_(R)','Resistance;Resistance Value','*'),
	 ('Resistor_Networks_and_Array---Resistance_UnitedValue','Resistance Value UnitedValue','*'),
	 ('Resistor_Networks_and_Array---Resistance_UnitedUnit','Resistance Value UnitedUnit','*'),
	 ('Resistor_Networks_and_Array---Tolerance','Tolerance','*'),
	 ('Resistor_Networks_and_Array---Rated_Power_(W)','Power Rating','*'),
	 ('Resistor_Networks_and_Array---Voltage_Rating_Max_(V)','Maximum Voltage Rating','*'),
	 ('Resistor_Networks_and_Array---Current_Sensing','Current Sensing','*'),
	 ('Resistor_Networks_and_Array---Maximum_Current_Rating_(A)','Maximum Current Rating',NULL);
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('Resistor_Networks_and_Array---Temperature_Coefficient_(ppm/C)','Temperature Coefficient','*'),
	 ('Mechanical_Switch---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('Mechanical_Switch---Switch_Configuration','Switch Configuration',NULL),
	 ('Mechanical_Switch---Actuator_Style','Actuator Style',NULL),
	 ('Mechanical_Switch---Type','Type',NULL),
	 ('Mechanical_Switch---Pole_Throw_Configuration','Pole Throw Configuration',NULL),
	 ('Mechanical_Switch---Current_Rating_Max_(A)','Maximum Current Rating','*'),
	 ('Mechanical_Switch---DC_Voltage_Rating_Max_(V)','Maximum DC Voltage Rating','*'),
	 ('Mechanical_Switch---Contact_Resistance_Max_(mR)','Maximum Contact Resistance','*'),
	 ('Mechanical_Switch---Operating_Force','Operating Force',NULL);
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('Mechanical_Switch---Operating_Life_(Cycles)','Operating Life;Electrical Life;Mechanical Life',NULL),
	 ('Thermistor---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('Thermistor---Resistance_@_25C_(R)','Resistance @ 25C','*'),
	 ('Thermistor---Percentage_of_Resistance_Tolerance_@_25C','Percentage of Resistance Tolerance @ 25C','*'),
	 ('Thermistor---Resistance_Range_@_25C_(R)','Resistance Range @ 25C',NULL),
	 ('Thermistor---Rated_Power_Max_(W)','Maximum Power Rating','*'),
	 ('Thermistor---Type','Type',NULL),
	 ('Varistor---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('Varistor---Varistor_Voltage_(V)','Varistor Voltage','*'),
	 ('Varistor---Capacitance_Value','Capacitance Value',NULL);
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('Varistor---Clamping_Voltage_(V)','Clamping Voltage',NULL),
	 ('Varistor---Clamping_Current_(A)','Clamping Current',NULL),
	 ('Varistor---AC_Voltage_Rating_Max_(V)','Maximum AC Voltage Rating',NULL),
	 ('Varistor---DC_Voltage_Rating_Max_(V)','Maximum DC Voltage Rating','*'),
	 ('Varistor---Maximum_Surge_Current_(A)','Maximum Surge Current','*'),
	 ('Varistor---Technology','Technology',NULL),
	 ('Capacitor_Film---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts',NULL),
	 ('Capacitor_Film---Type','Type',NULL),
	 ('Capacitor_Film---Capacitance_Value','Capacitance Value','*'),
	 ('Capacitor_Film---Tolerance','Tolerance','*');
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('Capacitor_Film---AC_Rated_Voltage_(VAC)','AC Rated Voltage',NULL),
	 ('Capacitor_Film---DC_Rated_Voltage_(VDC)','DC Rated Voltage','*'),
	 ('Capacitor_Film---Temperature_Coefficient','Dielectric',NULL),
	 ('Capacitor_Film---Voltage','Voltage','*'),
	 ('Capacitor_Tantalum_Solid---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts','*'),
	 ('Capacitor_Tantalum_Solid---Capacitance','Capacitance;Capacitance Value','*'),
	 ('Capacitor_Tantalum_Solid---Capacitance_Value','Capacitance Value UnitedValue','*'),
	 ('Capacitor_Tantalum_Solid---Capacitance_Unit','Capacitance Value UnitedUnit','*'),
	 ('Capacitor_Tantalum_Solid---Tolerance','Tolerance','*'),
	 ('Capacitor_Tantalum_Solid---DC_Rated_Voltage_(VDC)','DC Rated Voltage','*');
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('Capacitor_Tantalum_Solid---Voltage','Voltage','*'),
	 ('Capacitor_Tantalum_Solid---Equivalent_Series_Resistance_(R)','Equivalent Series Resistance','*'),
	 ('Capacitor_Tantalum_Solid---Family_Name','Family Name',NULL),
	 ('Capacitor_Tantalum_Solid---Case_Code','Case Code',NULL),
	 ('Capacitor_Tantalum_Solid---Type','Type',NULL),
	 ('RF_Filter---Type','Type',NULL),
	 ('RF_Filter---Center_Frequency_(MHz)','Center Frequency','*'),
	 ('RF_Filter---Bandwidth_(MHz)','Bandwidth','*'),
	 ('RF_Filter---Load_Impedance','Load Impedance','*'),
	 ('RF_Filter---Insertion_Loss_Max_(dB)','Maximum Insertion Loss','*');
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('RF_Filter---Pass_Band_Ripple_Max_(dB)','Maximum Pass Band Ripple',NULL),
	 ('RF_Filter---VSWR_Max','Maximum VSWR',NULL),
	 ('RF_Filter---Operating_Frequency_Max_(Hz)','Maximum Operating Frequency',NULL),
	 ('RF_Filter---Number_of_Terminals','Number of Terminals',NULL),
	 ('Digital_Filter---Type','Type',NULL),
	 ('Digital_Filter---Current_Rating_Max_(A)','Maximum Current Rating','*'),
	 ('Digital_Filter---Voltage_Rating_Max','Maximum Voltage Rating','*'),
	 ('Digital_Filter---Operating_Frequency_(Hz)','Operating Frequency','*'),
	 ('Digital_Filter---AC_Rated_Voltage_(V)','AC Rated Voltage',NULL),
	 ('Digital_Filter---Inductance_(mH)','Inductance','*');
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('Digital_Filter---Number_of_Phases','Number of Phases;Number of Elements',NULL),
	 ('Digital_Filter---Number_of_Terminals','Number of Terminals',NULL),
	 ('Digital_Filter---Capacitance_Value_(uF)','Capacitance Value','*'),
	 ('Digital_Filter---Leakage_Current_Max_(mA)','Maximum Leakage Current','*'),
	 ('Digital_Filter---Attenuation_Max_(dB)','Maximum Attenuation',NULL),
	 ('Transformer---Transformer_Type','Transformer Type',NULL),
	 ('Transformer---Turns_Ratio','Turns Ratio',NULL),
	 ('Transformer---Maximum_DCR_Primary_Side_(R)','Maximum DCR Primary Side',NULL),
	 ('Transformer---Maximum_DCR_Secondary_Side_(R)','Maximum DCR Secondary Side',NULL),
	 ('Transformer---Primary_Side_Impedance_(R)','Primary Side Impedance',NULL);
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('Transformer---Secondary_Side_Impedance_(R)','Secondary Side Impedance',NULL),
	 ('Transformer---Minimum_Return_Loss_(dB)','Minimum Return Loss',NULL),
	 ('Transformer---Maximum_Insertion_Loss_(dB)','Maximum Insertion Loss','*'),
	 ('Transformer---High_Potential','High Potential',NULL),
	 ('Transformer---Operating_Frequency','Operating Frequency',NULL),
	 ('Transformer---Operating_Frequency_Max_(kHz)','Maximum Operating Frequency',NULL),
	 ('Transformer---Rated_Power','Power Rating','*'),
	 ('Transformer---Output_Voltage_Max','Maximum Output Voltage','*'),
	 ('Transformer---Intput_Voltage_Max','Maximum Input Voltage','*'),
	 ('Transformer---Number_of_Terminals','Number of Terminals',NULL);
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('Mechanical---Type','Type','*'),
	 ('Module---Type','Type',NULL),
	 ('Photo_Couplers---Type','Coupling Type;Direction Type;Type',NULL),
	 ('Photo_Couplers---Number_of_Pins','Pin Count;Number of Terminals;Number of Contacts',NULL),
	 ('Photo_Couplers---Operating_Supply_Voltage_Max_(V)','Maximum Operating Supply Voltage',NULL),
	 ('Photo_Couplers---Forward_Voltage_Max_(V)','Maximum Forward Voltage',NULL),
	 ('Photo_Couplers---Forward_Current_Max_(mA)','Maximum Forward Current',NULL),
	 ('Photo_Couplers---Reverse_Voltage_Max_(V)','Maximum Reverse Voltage',NULL),
	 ('Photo_Couplers---Reverse_Current_Max_(uA)','Maximum Reverse Current',NULL),
	 ('Photo_Couplers---Power_Dissipation_Max_(mW)','Maximum Power Dissipation',NULL);
INSERT INTO bomgen_test.cdl_column_status (cdl_column_name,se_mapping_name,required) VALUES
	 ('Photo_Couplers---Input_Type','Input Type',NULL),
	 ('Photo_Couplers---Output_Type','Output Type',NULL),
	 ('Photo_Couplers---Number_of_Channels_per_Chip','Number of Channels per Chip',NULL);
